# fly.toml app configuration file generated for intercon-feedbacker on 2024-02-27T15:29:10-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'intercon-feedbacker'
primary_region = 'bos'

[build]

[env]
  PORT = "8080"
  DATABASE_SSL=1
  INTERCODE_CALLBACK_URL="https://survey.interconlarp.org/oauth_callback"
  INTERCODE_GRAPHQL_URL="https://neilhosting.net/graphql"
  INTERCODE_TOKEN_URL="https://neilhosting.net/oauth/token"
  INTERCODE_URL="https://neilhosting.net/oauth/authorize"
  NODE_ENV="production"
  PGSSLMODE="noverify"
  SESSION_TYPE="postgresql"
  CACHE_TYPE="local"
  TZ="America/New_York"

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
